name: Basic Continues Integration

on:
  pull_request:
    branches: [development]
jobs:
  basic_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup Node
        working-directory: ./Backend
        run: npm ci
      - name: Run test
        working-directory: ./Backend
        run: npm test